---
title: "Boosted regression trees for examining the effects of climate change on species distributions" 
author: "Victoria Prescott"
date: "03/02/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval=FALSE}
#Code modeled after:
#http://rspatial.org/sdm/rst/1_sdm_introduction.html
#https://cran.r-project.org/web/packages/dismo/vignettes/brt.pdf
#You will need the following packages:
library("dismo")
library("gbm")
library("maps")
library("mapdata")
library("maptools")
library("rgdal")
library("raster")
library("rasterVis")
```

```{r eval=FALSE}
#bring in tiff files for climate data and put them into one rasterstack
current.list=list.files(path="/postdoc/Bioclim/WorldClim/Current/tif_files", 
                        pattern="tif$", full.names=TRUE )
current=stack(current.list)

#RCP 45 2050
rcp45.50.list=list.files(path="/postdoc/Bioclim/Mod_WorldClim/Modlayers_2050_45/mod_50_45_tiff_gl", 
                         pattern="tif$", full.names=TRUE )
rcp45.50=stack(rcp45.50.list)

#RCP 45 2070
rcp45.70.list=list.files(path="/postdoc/Bioclim/Mod_WorldClim/Modlayers_2070_45/mod_70_45_tiff_gl", 
                         pattern="tif$", full.names=TRUE )
rcp45.70=stack(rcp45.70.list)

#RCP85 2050
rcp85.50.list=list.files(path="/postdoc/Bioclim/Mod_WorldClim/Modlayers_2050_85/mod_50_85_tiff_gl", 
                         pattern="tif$", full.names=TRUE )
rcp85.50=stack(rcp85.50.list)

#RCP85 2070
rcp85.70.list=list.files(path="/postdoc/Bioclim/Mod_WorldClim/Modlayers_2070_85/mod_70_85_tiff_gl", 
                         pattern="tif$", full.names=TRUE )
rcp85.70=stack(rcp85.70.list)

#great lakes current
gl.current.list=list.files(path="E:/BrokenHardDrive/postdoc/Bioclim/WorldClim/Current/tiff_gl_old",
                           pattern="tif$", full.names=TRUE)
gl.current=stack(gl.current.list)

#outline of great lakes basin
glb<-readOGR("/postdoc/glin_gl_mainlakes/gl_mainlakes.shp")
```

```{r eval=FALSE}
#bring in coordinates of species of interest
species<-list.files(path="E:/BrokenHardDrive/postdoc/analysis_files/training/global_training",
                    pattern="train_", full.names=TRUE)
```

```{r eval=FALSE}
#create training and test data for species presence
set.seed(0)
group=kfold(a.torren.coords, 5)
pres_train=a.torren.coords[group!=1,]
pres_test=a.torren.coords[group==1,]
```

```{r eval=FALSE}
#ALL models will be created in a for loop, using the training files in the 'species' list as a guide
for(i in 1:length(species)){
#get training coordinates of first species and get just the species name from the file
#species name will be used to get testing file
sp.coords.train<-read.csv(species[i], header=TRUE)
filename<-sub(pattern = "(.*)\\..*$", replacement = "\\1",
                basename(species[i]))
filename<-sapply(strsplit(filename, "train_"), "[[",-1)  
form1=sprintf('/postdoc/analysis_files/testing/global_test/test_%s.csv', filename)
sp.coords.test<-read.csv(file=form1)

#remove column that has species name
sp.coords.train<-sp.coords.train[,c("Longitude","Latitude")]
sp.coords.test<-sp.coords.test[,c("Longitude","Latitude")]
```

```{r eval=FALSE}
#get background training and testing data points
form_bg_train<-sprintf("/postdoc/analysis_files/train_background/%s.csv", filename)
backg_train<-read.csv(file=form_bg_train)
backg_train<-backg_train[,c("Longitude","Latitude")]
form_bg_test<-sprintf("/postdoc/analysis_files/test_background/%s.csv", filename)
backg_test<-read.csv(file=form_bg_test)
backg_test<-backg_test[,c("Longitude","Latitude")]
```

```{r eval=FALSE}
#create a map, showing just first raster layer 
#plot to check data
r=raster(current,1)
plot(!is.na(r), col=c('white','light grey'), legend=FALSE)
points(backg_train, pch='-', cex=0.5, col='yellow')
points(backg_test, pch='+', cex=0.5, col='black')
points(pres_train, pch='+', col='green')
points(pres_test, pch='+', col='blue')
```

```{r eval=FALSE}
#create data frame with presence and background training coordinates
#extract environmental data at those coordinates
backg_train_current<-extract(current, backg_train)
pres_train_current<-extract(current, pres_train)
pres_backg_train<-c(rep(1,nrow(pres_train_current)), 
                   rep(0, nrow(backg_train_current)))
train<-rbind(pres_train_current, backg_train_current)
envtrain<-data.frame(cbind(pa=pres_backg_train, train))
```

```{r eval=FALSE}
#do the same for test data
backg_test_current<-extract(current, backg_test)
pres_test_current<-extract(current, pres_test)
pres_backg_test<-c(rep(1,nrow(pres_test_current)), 
                   rep(0, nrow(backg_test_current)))
test<-rbind(pres_test_current, backg_test_current)
envtest<-data.frame(cbind(pa=pres_backg_test, test))
```

```{r eval=FALSE}
#run a model, lower the learning rate if you get the algorithm warning
sp.tc5.lr01.train<-gbm.step(data=envtrain, gbm.x=2:20, gbm.y=1,
                                  family="bernoulli", tree.complexity = 5,
                                  learning.rate=0.01, bag.fraction=0.5,
                                  n.folds=5)

#determine best number of trees
if (sp.tc5.lr01.train$gbm.call$best.trees > 1000) {
  
} else {
  sp.tc5.lr01.train<-gbm.step(data=envtrain, gbm.x=2:20, gbm.y=1,
                                    family="bernoulli", tree.complexity = 5,
                                    learning.rate=0.005, bag.fraction=0.5,
                                    n.folds=5)}
```

```{r eval=FALSE}

#determine how well the test data does with this model
predict_test=predict(sp.tc5.lr01.train,envtest, 
                     n.trees=sp.tc5.lr01.train$gbm.call$best.trees,
                     type="response")

calc.deviance(obs=envtest$pa, pred=predict_test, calc.mean = TRUE)
d<-cbind(envtest$pa, predict_test)
pres<-d[d[,1]==1,2]
abs<-d[d[,1]==0,2]
e<-evaluate(p=pres, a=abs)
e
#set threshold so that there is equal specificity and sensitivity
tr<-threshold(e, "equal_sens_spec")
sensitivity<-sum(pres>=tr)/length(pres) 
specificity<-sum(abs<tr)/length(abs)
TSS<-sensitivity + specificity - 1

#save calculated values
TSS<-data.frame(TSS)
TSS$sp<-filename
write.table(TSS,
            file="/postdoc/analysis_files/BRT_TSS/TSS.csv",
            append=T, sep=",", row.names=F, col.names = F)

sensitivity<-data.frame(sensitivity)
sensitivity$sp<-filename
write.table(sensitivity,
            file="/postdoc/analysis_files/BRT_sensitivity/sensitivity.csv",
            append=T, sep=",", row.names=F, col.names = F)

specificity<-data.frame(specificity)
specificity$sp<-filename
write.table(specificity,
            file="/postdoc/analysis_files/BRT_specificity/specificity.csv",
            append=T, sep=",", row.names=F, col.names = F)

tr<-data.frame(tr)
tr$sp<-filename
write.table(tr,
            file="/postdoc/analysis_files/BRT_threshold/threshold.csv",
            append=T, sep=",", row.names=F, col.names = F)

auc<-data.frame(e@auc)
auc$sp<-filename
write.table(auc,
            file="/postdoc/analysis_files/BRT_auc/auc.csv",
            append=T, sep=",", row.names=F, col.names = F)

trees<-sp.tc5.lr01.train$gbm.call$best.trees 
trees$sp<-filename
write.table(trees,
            file="/postdoc/analysis_files/BRT_trees/trees.csv",
            append=T, sep=",", row.names=F, col.names = F)

```

```{r eval=FALSE}
#this next step takes quite a while to run
#run the model across the great lakes (compare climate at gps points to the great lakes region)
current.predict<-predict(gl.current, sp.tc5.lr01.train,
           n.trees=sp.tc5.lr01.train$gbm.call$best.trees,
           type="response")

#save a png of the plot
colfun<-colorRampPalette(
  c("blue","cyan","green","yellow","red"))
png(paste0("/postdoc/analysis_files/png_files/current/current_", filename, ".png"))
current.plot<-levelplot(current.predict, 
          main=paste(filename, "current"), 
          xlim=c(-95,-70), ylim=c(40,52),
          at=seq(0,1, length.out=1000),
          col.regions=colfun,
          margin=F,
          maxpixels=13000000) +
  layer(sp.polygons(glb))
print(current.plot)
dev.off()
```

```{r eval=FALSE}
#repeat for intermediate climate change in 2050
rcp45.50.predict<-predict(rcp45.50,sp.tc5.lr01.train,
            n.trees=sp.tc5.lr01.train$gbm.call$best.trees,
            type="response")

png(paste0("/postdoc/analysis_files/png_files/4550/4550_", filename, ".png"))
plot.4550<-levelplot(rcp45.50.predict, 
          main=paste(filename, "RCP 4.5 2050"), 
          xlim=c(-95,-70), ylim=c(40,52),
          at=seq(0,1, length.out=1100),
          col.regions=colfun,
          margin=F,
          maxpixels=15000000) +
  layer(sp.polygons(glb))
print(plot.4550)
dev.off()

#repeat for intermediate climate change in 2070
rcp45.70.predict<-predict(rcp45.70, sp.tc5.lr01.train,
                         n.trees=sp.tc5.lr01.train$gbm.call$best.trees,
                         type="response")

png(paste0("/postdoc/analysis_files/png_files/4570/4570_", filename, ".png"))
plot.4570<-levelplot(rcp45.70.predict, 
          main=paste(filename, "RCP 4.5 2070"), 
          xlim=c(-95,-70), ylim=c(40,52),
          at=seq(0,1, length.out=1000),
          col.regions=colfun,
          margin=F,
          maxpixels=15000000) +
  layer(sp.polygons(glb))
print(plot.4570)
dev.off()

#repeat for high climate change in 2050
rcp85.50.predict<-predict(rcp85.50, sp.tc5.lr01.train,
                         n.trees=sp.tc5.lr01.train$gbm.call$best.trees,
                         type="response")

png(paste0("/postdoc/analysis_files/png_files/8550/8550_", filename, ".png"))
plot.8550<-levelplot(rcp85.50.predict, 
          main=paste(filename, "RCP 8.5 2050"), 
          xlim=c(-95,-70), ylim=c(40,52),
          at=seq(0,1, length.out=1100),
          col.regions=colfun,
          margin=F,
          maxpixels=15000000) +
  layer(sp.polygons(glb))
print(plot.8550)
dev.off()

#repeat for high climate change in 2070
rcp85.70.predict<-predict(rcp85.70, sp.tc5.lr01.train,
                         n.trees=sp.tc5.lr01.train$gbm.call$best.trees,
                         type="response")

png(paste0("/postdoc/analysis_files/png_files/8570/8570_", filename, ".png"))
plot.8570<-levelplot(rcp85.70.predict, 
          main=paste(filename, "RCP 8.5 2070"), 
          xlim=c(-95,-70), ylim=c(40,52),
          at=seq(0,1, length.out=1100),
          col.regions=colfun,
          margin=F,
          maxpixels=15000000) +
  layer(sp.polygons(glb))
print(plot.8570)
dev.off()

}

```

